/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bitmessage_jni_NativeNotBit */

#ifndef _Included_org_bitmessage_jni_NativeNotBit
#define _Included_org_bitmessage_jni_NativeNotBit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bitmessage_jni_NativeNotBit
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bitmessage_jni_NativeNotBit_connect
  (JNIEnv *, jobject);

/*
 * Class:     org_bitmessage_jni_NativeNotBit
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bitmessage_jni_NativeNotBit_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     org_bitmessage_jni_NativeNotBit
 * Method:    hasError
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_bitmessage_jni_NativeNotBit_hasError
  (JNIEnv *, jobject);

/*
 * Class:     org_bitmessage_jni_NativeNotBit
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_bitmessage_jni_NativeNotBit_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
